name: Spindly Build Webview

on:
  push:
    branches: [ master ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: APT update
      run: sudo apt-get update
    
    - name: Install packs
      run: sudo apt-get install -y libwebkit2gtk-4.0-dev

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      
    - name: NPM Install
      run: npm install
        
    - name: NPM Run build
      run: env SPINDLYBUILD=WEBVIEW npm run build
      
    - name: List published files
      run: ls -R published-app
        
    - name: Upload Build Artifact Linux
      uses: actions/upload-artifact@v2.3.1
      with:
        name: LinuxBuild
        path: published-app
        if-no-files-found: error
        retention-days: 90

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      
    - name: NPM Install
      run: npm install
        
    - name: NPM Run build
      run: env SPINDLYBUILD=WEBVIEW npm run build
      
    - name: List published files
      run: ls -R published-app
        
    - name: Upload Build Artifact Windows
      uses: actions/upload-artifact@v2.3.1
      with:
        name: WindowsBuild
        path: published-app
        if-no-files-found: error
        retention-days: 90
        
        
  build-MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      
    - name: NPM Install
      run: npm install
        
    - name: NPM Run build
      run: env SPINDLYBUILD=WEBVIEW npm run build
      
    - name: List published files
      run: ls -R published-app
        
    - name: Upload Build Artifact MacOS
      uses: actions/upload-artifact@v2.3.1
      with:
        name: MacOSBuild
        path: published-app
        if-no-files-found: error
        retention-days: 90
